
version: 2.1
jobs:
  deploy_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Deploy AWS infrastructure"
          command: |
            aws cloudformation deploy \
            --stack-name ci-infra \
            --template-body template.yaml \
            --region us-east-2 \
            --parameters parameters.json


workflows:
  aws-ci-workflow:
    jobs:
      - deploy_infra
