
version: 2.1
jobs:
  deploy_nw:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      # - run: echo $AWS_SECRET_ACCESS_KEY
      - run:
          name: "Deploy AWS nw"
          command: |
            aws cloudformation create-stack \
            --stack-name ci-nw \
            --template-body file://cf_templates/template_nw.yaml \
            --region us-east-2 \
            --parameters file://cf_templates/params_nw.json
      - run: sleep 60

  deploy_srv:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      # - run: echo $AWS_SECRET_ACCESS_KEY
      - run:
          name: "Deploy AWS srv"
          command: |
            aws cloudformation create-stack \
            --stack-name ci-srv \
            --template-body file://cf_templates/template_srv.yaml \
            --region us-east-2 \
            --parameters file://cf_templates/params_srv.json
      - run: sleep 60

  create_inv:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:  yum install -y tar gzip
      - run: echo "[all]" > inventory
      - run:
          name: "create ansible inventory file"
          command: |
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --output text >> inventory
      - run: ls
      - run: pwd
      - persist_to_workspace:
          root: ~/
          paths:
            - project/inventory

  configure_srv:
    docker:
      - image: python:3.10.0-alpine3.14
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["85:aa:65:37:70:da:ec:b2:79:db:af:99:23:6a:12:74"]
      - attach_workspace:
          at: ~/
      - run: 
          name: Install dependencies
          command: |
            apk add --update ansible
      - run: pwd
      - run: cat inventory
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory main.yml




workflows:
  aws-ci-workflow:
    jobs:
      - deploy_nw
      - deploy_srv:
          requires: ['deploy_nw']
      - create_inv:
          requires: ['deploy_srv']
      - configure_srv:
          requires: ['create_inv']
