# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09
Description: MV - Deployment of one server
Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    
  WebServerInstanceType:
    Description: Instance type
    Type: String

  AMI:
    Description: AMI used for the servers
    Type: String

Resources:

  EC2Instance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroupIds:
      - !Ref InstanceSecurityGroup
      ImageId: !Ref AMI
      KeyName: aws_mck_ohio
      InstanceType: !Ref WebServerInstanceType
      SubnetId : 
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PUB1-SN"

  EC2Instance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroupIds:
      - !Ref InstanceSecurityGroup
      ImageId: !Ref AMI
      KeyName: aws_mck_ohio
      InstanceType: !Ref WebServerInstanceType
      SubnetId : 
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PUB2-SN"

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22 and HTTP via port 80
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
